vcfa_url                  = "https://vcfa-vcf9-vip.corp.internal"
vcfa_username             = "admin"
vcfa_password             = "VMware1!VMware1!"
vcfa_project              = "acme"
vcfa_org                  = "acme"
supervisor_namespace_name = "sit-clj4z"
vcfa_region               = "emea"
cluster_name              = "tfsit"
